Add re-encoding feature

diff --git a/ffmerge b/ffmerge
--- a/ffmerge
+++ b/ffmerge
@@ -5,65 +5,108 @@
 # License: Open Source (MIT)
 # Copyright (c) 2018 Niranjan Kalyanasundaram
 
-# This script uses ffmpeg to merge all files with a given extension in a given directory
-# (without reencoding) using FFMPEG. For example, you could use this script to merge all
-# .mp4 files in a directory. It is assumed that all target files have originated from the
-# same device (encoded using the same codec, container, dimensions, etc). Files created from
-# different sources cannot be merged (see the ffmpeg concat command and -c flag for further
-# information).
+# This script uses ffmpeg to merge and re-encode all video files that contain a given text pattern in their filenames in a given directory.
+# The resulting file is optimized for streaming and saves disk space.
+# For example, you could use this script to merge and re-encode all video files that contain the text "episode" in their filenames in a directory.
 #
-# Usage: ffmerge [-h] targetfolder extension outfile
-# Example: ffmerge /usr/Videos .mp4 merged.mp4
+# Usage: ffmerg [-h] targetfoler pattern outfile
+# Example: ffmerge /usr/Videos "episode" merged
 
 display_usage() {
-    echo "ffmerge uses ffmpeg to merge video or audio files in a given folder"
-    echo "WARNING: It is assumed that all target files have originated from a single source (same codec, container, etc)"
-    echo "usage: ffmerge [-h] targetfolder extension outfile"
-    echo "example: ffmerge /usr/Videos .mp4 merged.mp4"
+    echo "ffmerge uses ffmpeg to merge and re-encode video files in a given folder"
+    echo "The resulting file is optimized for streaming and saves disk space."
+    echo "usage: ffmerge [-h] targetfoler pattern outfile"
+    echo "example: ffmerge /usr/Videos \"episode\" merged"
 }
 
+# Declare variables
+input_folder=$1
+pattern=$2
+output_file=$3
+temp_file=$(mktemp)
+initial_dir=`pwd`
+
 # Check for command line arguments
-if ! ([[ $1 ]] && [[ $2 ]] && [[ $3 ]])
+if ! ([[ $input_folder ]] && [[ $pattern ]] && [[ $output_file ]])
 then
     display_usage
     exit 1
 fi
 
 # Check for help flag
-if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]
+if [[ $input_folder == "-h" ]] || [[ $input_folder == "--help" ]]
 then
     display_usage
     exit 0
 fi
 
 # Check that input directory exists and is a directory
-if [[ ! -d $1 ]]
+if [[ ! -d $input_folder ]]
 then
-    echo "Error: $1 is not a valid directory"
+    echo "Error: $input_folder is not a valid directory"
     exit 1
 fi
 
-# Check that output file does not already exist
-if [[ -f $3 ]]
+# Check that output file does not have an extension
+if [[ "$output_file" == *.* ]]
 then
-    echo "Error: $3 already exists"
+    echo "Error: Output file must not have an extension"
     exit 1
 fi
 
-# Create temporary file for list of input files
-temp_file=$(mktemp)
+# Display the files in the input folder
+echo "Files in input folder:"
+for file in "$input_folder"/*
+do
+    if [[ $file == *"$pattern"* ]]
+    then
+        echo "$(tput setaf 2)$file$(tput sgr0)"
+    else
+        echo "$(tput setaf 1)$file$(tput sgr0)"
+    fi
+done
 
-# $1 contains target folder
-# $2 contains target file extension
-# $3 output file name
-INITIAL_DIR=`pwd`
+# Prompt the user to continue or exit
+echo "Do you want to continue? (y/n)"
+read -r continue_or_exit
+
+if [[ $continue_or_exit != "y" ]]
+then
+    exit 0
+fi
 
 echo "Generating list of input videos..."
 echo "# Videos to merge" > "$temp_file"
-find "$1" -name "*$2" -print0 | xargs -0 -I {} echo "file '{}'" >> "$temp_file"
+find "$input_folder" -name "*$pattern*" -print0 | xargs -0 -I {} echo "file '{}'" >> "$temp_file"
 echo "Input file generated!"
-echo "Using ffmpeg to merge files..."
-ffmpeg -f concat -safe 0 -i "$temp_file" -c copy -stats -y -loglevel warning -nostdin "$3"
+echo "Using ffmpeg to merge and re-encode files..."
+
+# Declare ffmpeg command and its arguments
+# The -f concat flag specifies that the input file
+# The -safe 0 flag disables the "unsafe" file name checks that are performed by ffmpeg
+# disables the "unsafe" file name checks that are performed by ffmpeg
+# The -i flag specifies the input file
+# The -vf scale=1280:-2,fps=30 flag combines the `scale` and `fps` video filters into a single filter
+# The -af aformat=channel_layouts=stereo flag sets the audio format to stereo
+# The -c:a aac flag specifies the audio codec to use (AAC)
+# The -c:v libx264 flag specifies the video codec to use (H.264)
+# The -crf 18 flag specifies the Constant Rate Factor (CRF) value to use for encoding
+# The -profile:v main flag specifies the H.264 profile to use
+# The -level 4.0 flag specifies the H.264 level to use
+# The -b:a 128k flag specifies the audio bitrate to use
+# The -b:v 1500k flag specifies the video bitrate to use
+# The -stats flag enables statistics about the input and output files to be printed
+# The -y flag overwrites the output file if it already exists
+# The -loglevel warning flag specifies a lower log level
+# The -nostdin flag prevents ffmpeg from reading from stdin
+ffmpeg_command=(ffmpeg -f concat -safe 0 -i "$temp_file" -vf scale=1280:-2,fps=30 -af aformat=channel_layouts=stereo -c:a aac -c:v libx264 -crf 18 -profile:v main -level 4.0 -b:a 128k -b:v 1500k -stats -y -loglevel warning -nostdin "$output_file.mp4")
+
+# Execute ffmpeg command
+"${ffmpeg_command[@]}"
+
+# Remove the temporary file
 rm "$temp_file"
-cd "$INITIAL_DIR"
-echo "Videos merged!"
+
+# Change back to the initial working directory
+cd "$initial_dir"
+echo "Videos merged and re-encoded!"
