Add efficiency and robustness improvements

diff --git a/ffmerge b/ffmerge
--- a/ffmerge
+++ b/ffmerge
@@ -4,38 +4,66 @@
 # Version: 1.0.0
 # License: Open Source (MIT)
 # Copyright (c) 2018 Niranjan Kalyanasundaram
-# Dependancy: ffmpeg
 
-# Script to merge all files (of a given extension) in a given directory (without reencoding) using FFMPEG (ex: all .mp4 files in ~/Movies )
-# It is assumed that all target files have originated from the same device (encoded using the same codec, container, dimensions, etc)
-# Files created from different sources cannot be merged (see ffmpeg concat command and -c flag for further info)
-# ffmerge <targetdir> <extension> <outfile>
+# This script uses ffmpeg to merge all files with a given extension in a given directory
+# (without reencoding) using FFMPEG. For example, you could use this script to merge all
+# .mp4 files in a directory. It is assumed that all target files have originated from the
+# same device (encoded using the same codec, container, dimensions, etc). Files created from
+# different sources cannot be merged (see the ffmpeg concat command and -c flag for further
+# information).
+#
+# Usage: ffmerge [-h] targetfolder extension outfile
+# Example: ffmerge /usr/Videos .mp4 merged.mp4
 
-if ! ([[ $1 ]] && [[ $2 ]] && [[ $3 ]])     
-# check for command line args
-then
+display_usage() {
     echo "ffmerge uses ffmpeg to merge video or audio files in a given folder"
     echo "WARNING: It is assumed that all target files have originated from a single source (same codec, container, etc)"
-    echo "usage: ffmerge targetfoler extension outfile"
+    echo "usage: ffmerge [-h] targetfolder extension outfile"
     echo "example: ffmerge /usr/Videos .mp4 merged.mp4"
-    exit
+}
+
+# Check for command line arguments
+if ! ([[ $1 ]] && [[ $2 ]] && [[ $3 ]])
+then
+    display_usage
+    exit 1
 fi
+
+# Check for help flag
+if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]
+then
+    display_usage
+    exit 0
+fi
+
+# Check that input directory exists and is a directory
+if [[ ! -d $1 ]]
+then
+    echo "Error: $1 is not a valid directory"
+    exit 1
+fi
+
+# Check that output file does not already exist
+if [[ -f $3 ]]
+then
+    echo "Error: $3 already exists"
+    exit 1
+fi
+
+# Create temporary file for list of input files
+temp_file=$(mktemp)
 
 # $1 contains target folder
 # $2 contains target file extension
 # $3 output file name
 INITIAL_DIR=`pwd`
-cd "$1"
+
 echo "Generating list of input videos..."
-echo "# Videos to merge" > concat.txt
-for file in *$2
-do
-    echo "file '$file'" >> concat.txt
-done
-echo "Input file genereated!"
+echo "# Videos to merge" > "$temp_file"
+find "$1" -name "*$2" -print0 | xargs -0 -I {} echo "file '{}'" >> "$temp_file"
+echo "Input file generated!"
 echo "Using ffmpeg to merge files..."
-ffmpeg -f concat -safe 0 -i concat.txt -c copy "$3"
-rm concat.txt
+ffmpeg -f concat -safe 0 -i "$temp_file" -c copy -stats -y -loglevel warning -nostdin "$3"
+rm "$temp_file"
 cd "$INITIAL_DIR"
 echo "Videos merged!"
-
